### PR TITLE
Updated readme with installation and configuration instructions

### PR DESCRIPTION
**Pull request by LavaTiger99**
Updated readme with installation and configuration instructions

### CODE REVIEW

**Comment by CappyT** [comment]
Add yourself to the special thanks!

(Maybe I should rename it as Contributors)

**Comment by LavaTiger99** [comment]
Done.

**Comment by CappyT** [comment]
Also, as I side note: I'm currently using it as a script, you may have noticed that the exe version doesn't work. (it's a problem I'm facing with pyinstaller)

If you want to try it, install the dependencies with pip, then you can do that the following way:
Win + R to open the "Run" window. Type taskschd.msc
Create a new activity and set it like this (screens are in Italian, but you can figure out by the position of the UI elements):

immagine
immagine

Here is important to set "Start in" folder, otherwise, the script cannot get the configuration file:
Arguments box is set to: C:\Users\CappyT\Documents\Repos\g14control\main.pyw
Start in box is set to: C:\Users\CappyT\Documents\Repos\g14control
immagine

immagine

**Comment by LavaTiger99** [comment]
Closed pull request, new pull request using branch Issue5: #6

**Pull request closed without merging**
